### ISSUE TITLE
missing english README

### ISSUE THREAD

**Issue by raphaelauv** [szstonelee/redrock#1]
the old readme was in english -> https://github.com/szstonelee/redrock_old

could you add to the current readme a link to an english README

thanks :+1:

**Comment by szstonelee** [comment]
The old link has been added to README. and note: The RedRock project is completely re-written for code. I suggest the new one for RedRock. But the documents of RedRock are now only for Chinese. Please use some translation tool for the documents. I am sorry about that.

**Comment by raphaelauv** [comment]
https://github.com/szstonelee/redrock/pull/5
